apiVersion: v1
kind: PersistentVolume
metadata:
  name: serverfiles-pv
  namespace: 5stack
spec:
  capacity:
    storage: 75Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/5stack/serverfiles
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: 5stack-services
          operator: In
          values:
          - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: serverfiles-pvc
  namespace: 5stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 75Gi
  volumeName: serverfiles-pv