apiVersion: v1
kind: PersistentVolume
metadata:
  name: steamcmd-pv
  namespace: 5stack
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/5stack/steamcmd
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: 5stack-services
          operator: In
          values:
          - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: steamcmd-pvc
  namespace: 5stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  volumeName: steamcmd-pv 