apiVersion: v1
kind: PersistentVolume
metadata:
  name: timescaledb-pv
  namespace: 5stack
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/5stack/timescaledb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: 5stack-timescaledb
          operator: In
          values:
          - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-pvc
  namespace: 5stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
  volumeName: timescaledb-pv