apiVersion: v1
kind: PersistentVolume
metadata:
  name: typesense-pv
  namespace: 5stack
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/5stack/typesense
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: 5stack-services
          operator: In
          values:
          - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: typesense-pvc
  namespace: 5stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
  volumeName: typesense-pv  