apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nvidia-time-slicing.yaml
  - nvidia-plugin.yaml
  - game-server-node-connector-nvidia.yaml

secretGenerator:
  - name: hasura-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - ../local-secrets/hasura-secrets.env
  - name: redis-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - ../local-secrets/redis-secrets.env
