apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-game-stream
  namespace: 5stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-game-stream
  template:
    metadata:
      labels:
        app: dev-game-stream
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: 5stack-dev-server
                operator: In
                values:
                  - "true"
      containers:
        - image: ghcr.io/5stackgg/game-stream:latest
          command: ["sleep"]
          args: ["infinity"]
          name: dev-game-stream
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: dev-game-stream-secrets
          env:
            - name: SERVER_IP
              value: '68.38.242.60'          
            - name: SERVER_PORT
              value: '27020'
          volumeMounts:
            - name: steamcmd
              mountPath: /serverdata/steamcmd
            - name: serverfiles
              mountPath: /serverdata/serverfiles
      volumes:
        - name: steamcmd
          hostPath:
            path: /opt/5stack/steamcmd
            type: Directory
        - name: serverfiles
          hostPath:
            path: /opt/5stack/serverfiles
            type: Directory