apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 5stack

resources:
  - deployment.yaml
  - service.yaml

secretGenerator:
  - name: dev-game-stream-secrets
    envs:
      - dev-game-stream-secrets.env