apiVersion: v1
kind: Service
metadata:
  name: dev-game-stream
  namespace: 5stack
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: dev-game-stream
  type: NodePort
