apiVersion: v1
kind: Service
metadata:
  name: dev-game-stream
  namespace: 5stack
spec:
  ports:
    - name: vnc
      port: 8083
      protocol: TCP
      targetPort: 8083
    - name: hud
      port: 31982
      protocol: TCP
      targetPort: 31982
      
  selector:
    app: dev-game-stream
  type: NodePort
