apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: steam-headless
spec:
  serviceName: "steam-headless"
  replicas: 1
  selector:
    matchLabels:
      app: steam-headless
  template:
    metadata:
      labels:
        app: steam-headless
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: 5stack-dev-server
                operator: In
                values:
                  - "true"
      runtimeClassName: nvidia
      securityContext:
        fsGroup: 1000
      containers:
      - name: steam-headless
        securityContext:
          privileged: true
        image: josh5/steam-headless:latest
        resources:
          requests:
            memory: "2G"
            cpu: "2"
          limits:
            memory: "10G"
            cpu: "4"
            nvidia.com/gpu: 1
        ports:
        - containerPort: 8083
          protocol: TCP
        - containerPort: 31982
          protocol: TCP
        volumeMounts:
        - name: home-dir
          mountPath: /home/default/
        - name: games-dir
          mountPath: /mnt/games/
        - name: input-devices
          mountPath: /dev/input/
        - name: dshm
          mountPath: /dev/shm
        env:
        - name: NAME
          value: 'SteamHeadless'
        - name: TZ
          value: 'America/New_York'
        - name: USER_LOCALES
          value: 'en_US.UTF-8 UTF-8'
        - name: DISPLAY
          value: ':55'
        - name: SHM_SIZE
          value: '2G'
        - name: DOCKER_RUNTIME
          value: 'nvidia'
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: UMASK
          value: '000'
        - name: USER_PASSWORD
          value: 'password'
        - name: MODE
          value: 'primary'
        - name: WEB_UI_MODE
          value: 'vnc'
        - name: ENABLE_VNC_AUDIO
          value: 'false'
        - name: PORT_NOVNC_WEB
          value: '8083'
        - name: NEKO_NAT1TO1
          value: ''
        - name: ENABLE_SUNSHINE
          value: 'false'
        - name: ENABLE_EVDEV_INPUTS
          value: 'true'
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: 'all'
        - name: NVIDIA_VISIBLE_DEVICES
          value: 'all'
      volumes:
      - name: home-dir
        hostPath:
          path: /opt/5stack/steam/home
          type: Directory
      - name: games-dir
        hostPath:
          path: /opt/5stack/steam/games
          type: Directory
      - name: input-devices
        hostPath:
          path: /dev/input/
      - name: dshm
        emptyDir:
          medium: Memory