apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: 5stack
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: server-creator
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: 5stack-api
                operator: In
                values:
                  - "true"
      containers:
        - image: ghcr.io/5stackgg/api:latest
          name: api
          ports:
            - containerPort: 5585
          startupProbe:
            httpGet:
              path: /system/healthz
              port: 5585
            periodSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /system/healthz
              port: 5585
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 2
          livenessProbe:
            httpGet:
              path: /system/healthz
              port: 5585
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 3
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:  
                name: api-secrets
            - secretRef:  
                name: steam-secrets
            - secretRef:
                name: hasura-secrets
            - secretRef:  
                name: typesense-secrets
            - secretRef:
                name: discord-secrets
            - secretRef:
                name: redis-secrets
            - secretRef:
                name: timescaledb-secrets
            - secretRef:
                name: tailscale-secrets
            - secretRef:
                name: s3-secrets
            - configMapRef:
                name: s3-config
            - secretRef:
                name: faceit-secrets