apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 5stack

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: coturn-config
    namespace: 5stack
    files:
      - turnserver.conf

  - name: coturn-env
    namespace: 5stack
    envs:
      - coturn.env
