apiVersion: v1
kind: Service
metadata:
  name: coturn
  namespace: 5stack
  labels:
    app: coturn
spec:
  selector:
    app: coturn
  ports:
    - { name: turn-udp, port: 3478, targetPort: 3478, protocol: UDP }
    - { name: turn-tcp, port: 3478, targetPort: 3478, protocol: TCP }
