apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - daemonset.yaml
  - rbac/cluster-role-binding.yaml
  - rbac/cluster-role.yaml
  - rbac/role-binding.yaml
  - rbac/role.yaml