apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-yaml
  namespace: 5stack
data:
  redis.conf: |
    tcp-keepalive 240
    appendonly no
    save ""
    maxmemory-policy noeviction
    requirepass ${REDIS_PASSWORD}
    io-threads-do-reads yes
    io-threads ${IO_THREADS}