apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: 5stack
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: 5stack-redis
                operator: In
                values:
                  - "true"
      containers:
      - name: redis
        image: redis:7.4-alpine
        ports:
        - containerPort: 6379
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
        startupProbe:
          tcpSocket:
            port: 6379
          periodSeconds: 5
          failureThreshold: 60
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
        envFrom:
          - secretRef:
              name: redis-secrets 
        command:
        - sh
        - -c
        - |
          sed -e "s/\${REDIS_PASSWORD}/$REDIS_PASSWORD/g" /redis-config/redis.conf > /tmp/redis.conf && redis-server /tmp/redis.conf
        volumeMounts:
        - name: redis-config
          mountPath: /redis-config
      volumes:
      - name: redis-config
        configMap:
          name: redis-config

