apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: 5stack
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: 5stack-redis
                operator: In
                values:
                  - "true"
      containers:
      - name: redis
        image: redis:8.2-alpine
        ports:
        - containerPort: 6379
          protocol: TCP
        startupProbe:
          tcpSocket:
            port: 6379
          periodSeconds: 5
          failureThreshold: 12
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 2
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 15
          failureThreshold: 3
        envFrom:
          - secretRef:
              name: redis-secrets 
          - configMapRef:
              name: redis-config
        command:
        - sh
        - -c
        - |
          cp /redis-yaml/redis.conf /tmp/redis.conf
          sed -i "s/\${REDIS_PASSWORD}/$REDIS_PASSWORD/g" /tmp/redis.conf
          sed -i "s/\${IO_THREADS}/$IO_THREADS/g" /tmp/redis.conf
          redis-server /tmp/redis.conf
        volumeMounts:
        - name: redis-yaml
          mountPath: /redis-yaml
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-yaml
        configMap:
          name: redis-yaml
      - name: redis-data
        hostPath:
          path: /opt/5stack/redis
          type: DirectoryOrCreate