# Allow NGINX ingress controller to reach web, api, hasura, minio, typesense
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-services
  namespace: 5stack
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values: [web, api, hasura, minio, typesense]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - port: 3000
          protocol: TCP
        - port: 5585
          protocol: TCP
        - port: 8080
          protocol: TCP
        - port: 9000
          protocol: TCP
        - port: 9090
          protocol: TCP
        - port: 8108
          protocol: TCP
  policyTypes:
    - Ingress
