apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: 5stack
  name: 5stack-ssl
spec:
  secretName: 5stack-ssl
  renewBefore: 240h
  duration: 2160h
  dnsNames:
  - ${WEB_DOMAIN}
  - ${API_DOMAIN}
  - ${DEMOS_DOMAIN}
  - ${TYPESENSE_HOST}
  - ${S3_CONSOLE_HOST}
  - ${WS_DOMAIN}
  issuerRef:
    name: 5stack-issuer
    kind: Issuer