apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod
  namespace: 5stack
spec:
  secretName: secret-tls
  renewBefore: 240h
  duration: 2160h
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer