apiVersion: v1
kind: Service
metadata:
  name: dev-game-server-node-connector
  namespace: 5stack
spec:
  ports:
    - port: 7080
      protocol: TCP
  selector:
    app: dev-game-server-node-connector