apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

secretGenerator:
  - name: api-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - api-secrets.env

  - name: timescaledb-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - timescaledb-secrets.env
  - name: tailscale-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - tailscale-secrets.env
  - name: steam-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - steam-secrets.env
  - name: hasura-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - hasura-secrets.env
  - name: discord-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - discord-secrets.env
  - name: s3-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - s3-secrets.env
  - name: redis-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - redis-secrets.env
  - name: typesense-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - typesense-secrets.env
  - name: minio-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - minio-secrets.env
  - name: faceit-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - faceit-secrets.env

patches:
  - target:
      kind: Deployment
      name: api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/1/secretRef/name
        value: api-secrets
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/2/secretRef/name
        value: steam-secrets
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/3/secretRef/name
        value: hasura-secrets
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/4/secretRef/name
        value: typesense-secrets
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/5/secretRef/name
        value: discord-secrets
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/6/secretRef/name
        value: redis-secrets
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/7/secretRef/name
        value: timescaledb-secrets
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/8/secretRef/name
        value: tailscale-secrets
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/9/secretRef/name
        value: s3-secrets
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/11/secretRef/name
        value: faceit-secrets

  - target:
      kind: Deployment
      name: hasura
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
        value: hasura-secrets
      - op: replace
        path: /spec/template/spec/containers/0/env/10/valueFrom/secretKeyRef/name
        value: timescaledb-secrets
      - op: replace
        path: /spec/template/spec/initContainers/0/envFrom/1/secretRef/name
        value: api-secrets
      - op: replace
        path: /spec/template/spec/initContainers/0/envFrom/2/secretRef/name
        value: steam-secrets
      - op: replace
        path: /spec/template/spec/initContainers/0/envFrom/3/secretRef/name
        value: hasura-secrets
      - op: replace
        path: /spec/template/spec/initContainers/0/envFrom/4/secretRef/name
        value: typesense-secrets
      - op: replace
        path: /spec/template/spec/initContainers/0/envFrom/5/secretRef/name
        value: discord-secrets
      - op: replace
        path: /spec/template/spec/initContainers/0/envFrom/6/secretRef/name
        value: redis-secrets
      - op: replace
        path: /spec/template/spec/initContainers/0/envFrom/7/secretRef/name
        value: timescaledb-secrets
      - op: replace
        path: /spec/template/spec/volumes/1/secret/secretName
        value: timescaledb-secrets

  - target:
      kind: Deployment
      name: redis
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
        value: redis-secrets

  - target:
      kind: StatefulSet
      name: minio
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/1/secretRef/name
        value: minio-secrets
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/2/secretRef/name
        value: s3-secrets

  - target:
      kind: StatefulSet
      name: timescaledb
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
        value: timescaledb-secrets
      - op: replace
        path: /spec/template/spec/containers/0/env/3/valueFrom/secretKeyRef/name
        value: api-secrets
      - op: replace
        path: /spec/template/spec/volumes/0/secret/secretName
        value: api-secrets

  - target:
      kind: StatefulSet
      name: typesense
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/1/secretRef/name
        value: typesense-secrets

  - target:
      kind: DaemonSet
      name: game-server-node-connector
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
        value: hasura-secrets
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/1/secretRef/name
        value: redis-secrets 