apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-app-key
  namespace: 5stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-5stack
    kind: SecretStore
  target:
    name: api-app-key
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: api
        property: APP_KEY
