apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coturn-secrets
  namespace: 5stack
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: secretstore-5stack
    kind: SecretStore
  target:
    name: coturn-secrets
  data:
    - secretKey: TURN_SECRET
      remoteRef:
        key: coturn
        property: TURN_SECRET
