apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: push-secrets
  namespace: 5stack
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: secretstore-5stack
    kind: SecretStore
  target:
    name: push-secrets
  data:
    - secretKey: WEB_PUSH_PUBLIC_KEY
      remoteRef:
        key: push
        property: WEB_PUSH_PUBLIC_KEY
    - secretKey: WEB_PUSH_PRIVATE_KEY
      remoteRef:
        key: push
        property: WEB_PUSH_PRIVATE_KEY
