apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-secrets
  namespace: 5stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-5stack
    kind: SecretStore
  target:
    name: tailscale-secrets
  data:
    - secretKey: TAILSCALE_AUTH_KEY
      remoteRef:
        key: tailscale
        property: TAILSCALE_AUTH_KEY 