apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

secretGenerator:
  - name: dev-server-secrets
    envs:
      - dev-server-secrets.env
  - name: steam-secrets
    envs:
      - steam-secrets.env