apiVersion: v1
kind: Service
metadata:
  name: dev-cs-server
  namespace: 5stack
spec:
  ports:
    - name: rcon
      port: 27015
      protocol: TCP
      targetPort: 27015
    - name: game
      port: 27015
      protocol: UDP
      targetPort: 27015
    - name: tv
      port: 27020
      protocol: TCP
      targetPort: 27020
    - name: tv-udp
      port: 27020
      protocol: UDP
      targetPort: 27020
  selector:
    app: dev-cs-server
  type: NodePort
