apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snapshot
  namespace: 5stack
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /game-streamer/$1/snapshot
    nginx.ingress.kubernetes.io/proxy-body-size: "2m"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Accept, If-None-Match"
spec:
  ingressClassName: nginx
  rules:
    - host: ${GAME_STREAM_DOMAIN}
      http:
        paths:
          - path: /snapshot/(.+)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api
                port:
                  number: 5585
