apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: game-server-node-connector-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: game-server-node-connector
  namespace: 5stack
roleRef:
  kind: ClusterRole
  name: game-server-node-connector-clusterrole
  apiGroup: rbac.authorization.k8s.io