apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: game-server-node-connector-rolebinding
  namespace: 5stack
subjects:
- kind: ServiceAccount
  name: game-server-node-connector
  namespace: 5stack
roleRef:
  kind: Role
  name: game-server-node-connector-role
  apiGroup: rbac.authorization.k8s.io