apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - api
  - game-server-node-connector
  - hasura
  - minio
  - timescaledb
  - redis
  - typesense
  - web
  - volumes
  - nginx 


configMapGenerator:
  - name: api-config
    namespace: 5stack
    envs:
      - properties/api-config.env
  - name: typesense-config
    namespace: 5stack
    envs:
      - properties/typesense-config.env
    behavior: merge
  - name: s3-config
    namespace: 5stack
    envs:
      - properties/s3-config.env
  - name: nginx-config
    namespace: 5stack
    envs:
      - properties/nginx-config.env

replacements:
- source:
    kind: ConfigMap
    name: api-config
    fieldPath: data.WS_DOMAIN
  targets:
  - select:
      kind: Ingress
      name: ws
    fieldPaths:
    - spec.rules.0.host
- source:
    kind: ConfigMap
    name: api-config
    fieldPath: data.API_DOMAIN
  targets:
  - select:
      kind: Ingress
      name: api
    fieldPaths:
    - spec.rules.0.host
- source:
    kind: ConfigMap
    name: api-config
    fieldPath: data.DEMOS_DOMAIN
  targets:
  - select:
      kind: Ingress
      name: demos
    fieldPaths:
    - spec.rules.0.host
- source:
    kind: ConfigMap
    name: api-config
    fieldPath: data.WEB_DOMAIN
  targets:
  - select:
      kind: Ingress
      name: api
    fieldPaths:
    - spec.rules.1.host
  - select:
      kind: Ingress
      name: web
    fieldPaths:
    - spec.rules.0.host
- source:
    kind: ConfigMap
    name: s3-config
    fieldPath: data.S3_CONSOLE_HOST
  targets:
  - select:
      kind: Ingress
      name: s3-console
    fieldPaths:
    - spec.rules.0.host
- source:
    kind: ConfigMap
    name: typesense-config
    fieldPath: data.TYPESENSE_HOST
  targets:
  - select:
      kind: Ingress
      name: typesense
    fieldPaths:
    - spec.rules.0.host
- source:
    kind: ConfigMap
    name: nginx-config
    fieldPath: data.HTTP_PORT
  targets:
  - select:
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
    fieldPaths:
    - spec.ports.0.port
- source:
    kind: ConfigMap
    name: nginx-config
    fieldPath: data.HTTPS_PORT
  targets:
  - select:
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
    fieldPaths:
    - spec.ports.1.port

# Note: secretGenerator has been moved to overlays/secrets
# Use overlays/secrets when VAULT_MANAGER=false
# Use overlays/vault when VAULT_MANAGER=true