apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: server-creator-role
  namespace: 5stack
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - create
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - create
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - ''
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - list
  - apiGroups:
      - ''
    resources:
      - pods/exec
    verbs:
      - create
      - get
  - apiGroups:
      - 'batch'
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - get