apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: server-creator-binding
  namespace: 5stack
subjects:
- kind: ServiceAccount
  name: server-creator
  namespace: 5stack
roleRef:
  kind: Role
  name: server-creator-role
  apiGroup: rbac.authorization.k8s.io