apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
  namespace: 5stack
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          backoffLimit: 0
          containers:
            - name: pgdump-container
              image: postgres:latest
              command: ["/bin/sh", "-c"]
              args:
                - |
                  apt-get update && apt-get install -y curl && \
                  mkdir -p /opt/backups && \
                  PGPASSWORD="{{ POSTGRES_PASSWORD }}" pg_dump -h postgres -U "{{ POSTGRES_USER }}" -d "{{ POSTGRES_DB }}" -Fc > /opt/backups/`date +%Y%m%d%H%M%S`.dump  && \
                  find /opt/backups/ -name '*' -type f -exec curl -u {{ BACKUP_USERNAME }}:{{ BACKUP_PASSWORD }} -T {} {{ BACKUP_HOST }}/remote.php/dav/files/{{ BACKUP_USERNAME }}/5stack/db-backups/ \;
          restartPolicy: Never


